version: 2

jobs:
  build:
    docker:
      - image: vapor/swift:5.0
    steps:
      - checkout
      - run: swift build
      - run: swift test
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - linux
      - linux-release
