name: Build

on: [push]

jobs:
  macOS:
    name: Build on macOS-latest
    container: 
      image: swift:latest
        
    runs-on: macOS-latest
        
    steps:
    - name: Print Swift version
      run: swift --version
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Swift build
      run: swift build -c release
            
    - name: Done
      run: echo Done
      
  ubuntu:
    name: Build on ubuntu-latest
    container: 
      image: swift:latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Swift build
      run: swift build -c release
            
    - name: Done
      run: echo Done
