name: Ubuntu 20.04 Swift latest

on: [push]

jobs:
  swift-docker:
    container: 
      image: swift:latest
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Swift build
      run: swift build -c release
            
    - name: Done
      run: echo Done
