name: Build on macOS and Ubuntu latest

on: [push]

jobs:
#  macOS:
#    name: Build on macOS-latest
#    runs-on: macOS-latest
#        
#    steps:
#    - name: Print Swift version
#      run: swift --version
#      
#    - name: Checkout
#      uses: actions/checkout@master
#
#    - name: Swift build
#      run: swift build -c release
#            
#    - name: Done
#      run: echo Done
      
  ubuntu:
    name: Build on ubuntu-latest
    strategy:
      matrix:
        swift: [5.8.1] # [5.8.1, 5.7.3, 5.6.3]
    container: swift:${{matrix.swift}}
    services:
       couchdb:
         image: couchdb
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Swift build
      run: swift build -c release
      
    - name: Swift test
      run: swift test
            
    - name: Done
      run: echo Done
